export const SEARCH_CAROUSEL = 'SEARCH_CAROUSEL';
export const SEARCH_RECIPE = 'SEARCH_RECIPE';
export const UPDATE_RECIPE = 'UPDATE_RECIPE';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GET_USERSUCCESS = 'GET_USERSUCCESS';
export const GET_USERFAIL = 'GET_USERFAIL';
